[build]
  # 构建命令
  command = "npm run build"

  # 输出目录
  publish = "dist"

  # 基础目录
  base = "frontend"

[build.environment]
  # Node.js 版本
  NODE_VERSION = "18"

  # API URL环境变量
  VITE_API_URL = "https://stylist-agent2-production-2.up.railway.app/api"

# SPA重定向规则 - 所有路由都指向index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 安全头部
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 缓存策略
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 首页和HTML文件不缓存
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"